version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8000:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/localhost.crt:/etc/nginx/certs/localhost.crt
      - ./ssl/localhost.key:/etc/nginx/certs/localhost.key
      - ./ssl/ssl_password:/etc/nginx/ssl_password
      - ./app:/app
    networks:
      - my_network

  php:
    container_name: php
    build:
      context: ./
    environment:
      PHP_IDE_CONFIG: "serverName=${SERVER_NAME}"
    volumes:
      - ./app:/app
    networks:
      - my_network

  db:
    container_name: db
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    external: false