twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        telegram_redirect_url: '%env(TELEGRAM_URL)%'

when@test:
    twig:
        strict_variables: true
